# Generated by Django 4.2.7 on 2024-03-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("Guide", "Guide"),
                    ("Tourist", "Tourist"),
                    ("Administrator", "Administrator"),
                    ("Accountant", "Accountant"),
                    ("Moderator", "Moderator"),
                ],
                default="UNA",
                max_length=20,
            ),
        ),
    ]
