# Generated by Django 4.2.7 on 2024-04-21 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_room_reservation_hotelijerprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hotelijerprofile",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="hotelijerprofile",
            name="room",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="users.room"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("Guide", "Guide"),
                    ("Tourist", "Tourist"),
                    ("Administrator", "Administrator"),
                    ("Accountant", "Accountant"),
                    ("Moderator", "Moderator"),
                    ("Hotelijer", "Hotelijer"),
                ],
                default="UNA",
                max_length=20,
            ),
        ),
    ]
