# Generated by Django 4.2.7 on 2024-04-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_hotelijerprofile_balance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_number",
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
