# Generated by Django 4.2.7 on 2024-04-21 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_reservation_id_alter_room_room_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hotelijerprofile",
            name="room",
        ),
        migrations.AddField(
            model_name="hotelijerprofile",
            name="rooms",
            field=models.ManyToManyField(to="users.room"),
        ),
    ]
