# Generated by Django 4.2.7 on 2024-04-21 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_remove_hotelijerprofile_room_hotelijerprofile_rooms"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="hotelijer",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="hotelijerprofile",
            name="hotelijer",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="hotelijerprofile",
            name="rooms",
            field=models.ManyToManyField(
                null=True, related_name="hotelijeri", to="users.room"
            ),
        ),
    ]
