# Generated by Django 4.2.7 on 2024-04-28 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_room_hotelijer_alter_hotelijerprofile_hotelijer_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                ("contractId", models.AutoField(primary_key=True, serialize=False)),
                ("hotelijerName", models.CharField(max_length=100)),
                ("hotelijerMessage", models.CharField(max_length=1000)),
                ("withdrawCondition", models.CharField(max_length=1000)),
                ("percentage", models.DecimalField(decimal_places=0, max_digits=3)),
                ("date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "hotelijerId",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
