# Generated by Django 4.2.7 on 2024-04-28 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_contract"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "PENDING"),
                    ("rejected", "REJECTED"),
                    ("accepted", "ACCEPTED"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
