# Generated by Django 4.2.7 on 2024-04-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_contract_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="hotelijerId",
            field=models.IntegerField(),
        ),
    ]
