# Generated by Django 4.2.7 on 2024-05-19 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_contract_hotelijerid"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotelijerprofile",
            name="percentage",
            field=models.IntegerField(default=0),
        ),
    ]
